/* eslint-disable sonarjs/no-duplicate-string */
export const sampleProductDetail = {
  id: 1,
  name: "Smartphone",
  description: "High-end smartphone with advanced features.",

  //TODO:   Add more fields for product details like
  //     - description,
  //     - size & fit,
  //     - material & care,
  //     - specifications,
  //         Sleeve Length
  //         Shape
  //         Neck
  //         Print or Pattern Type
  //         Design Styling
  //         Slit Detail
  //         Ornamentation
  //         Length
  //         Hemline
  //         Color Family
  //         Weave Pattern
  //         Weave Type
  //         Occasion
  //         Number of Items

  price: 599.99,
  currency: "Rs",
  image: ["https://picsum.photos/200/300", "https://i.imgur.com/ErYYZnT.jpeg", "https://i.imgur.com/boBPwYW.jpeg"], // array for multiple images
  discount: 10,
  availability: true,
  brand: "BrandX",
  rating: 4.5,
  size: ["S", "M", "L", "XL"],
  reviews: [
    {
      user_id: 1,
      rating: 5,
      comment: "Great phone with a superb camera!",
    },
    {
      user_id: 2,
      rating: 4,
      comment: "Good performance, but the battery life could be better.",
    },
  ],
  category: [
    {
      id: 1,
      name: "Sarees",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
    },
    {
      id: 2,
      name: "Kurtas",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
    },
    {
      id: 3,
      name: "Kurtas Set",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
    },
  ],
  color: [
    {
      id: 1,
      name: "Red",
      hex: "#FF0000",
    },
    {
      id: 2,
      name: "Green",
      hex: "#00FF00",
    },
    {
      id: 3,
      name: "Blue",
      hex: "#0000FF",
    },
  ],
  tags: ["women", "men", "girls", "boy"],
};

// export const responseData = {
//   count: 10,
//   products: [
//     {
//       id: 1,
//       name: "Amet minim mollit",
//       price: 1200,
//       currency: "Rs",
//       image: ["https://picsum.photos/200/300"],
//       discount: 10,
//       availability: true,
//       brand: "BrandX",
//       rating: 4.5,
//     },
//   ],
// };

export const responseData = [
  {
    id: 1,
    name: "quis",
    price: 355,
    currency: "Rs",
    image: ["https://picsum.photos/200/300"],
    discount: 20,
    availability: true,
    brand: "Zooxo",
    rating: 0.4,
  },
  {
    id: 2,
    name: "pellentesque volutpat dui",
    price: 1562,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 75,
    availability: true,
    brand: "Meedoo",
    rating: 1.0,
  },
  {
    id: 3,
    name: "in",
    price: 181,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 20,
    availability: false,
    brand: "Lazzy",
    rating: 0.6,
  },
  {
    id: 4,
    name: "et",
    price: 1840,
    currency: "Rs",
    image: ["https://picsum.photos/200/300"],
    discount: 75,
    availability: false,
    brand: "Trilia",
    rating: 2.7,
  },
  {
    id: 5,
    name: "vestibulum",
    price: 952,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 55,
    availability: true,
    brand: "Ooba",
    rating: 2.5,
  },
  {
    id: 6,
    name: "sit amet",
    price: 208,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 20,
    availability: false,
    brand: "Babblestorm",
    rating: 0.6,
  },
  {
    id: 7,
    name: "lacinia",
    price: 1466,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 40,
    availability: true,
    brand: "Agivu",
    rating: 1.2,
  },
  {
    id: 8,
    name: "pellentesque",
    price: 1153,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 80,
    availability: false,
    brand: "Meembee",
    rating: 3.8,
  },
  {
    id: 9,
    name: "rhoncus",
    price: 1377,
    currency: "Rs",
    image: ["https://picsum.photos/200/300"],
    discount: 25,
    availability: true,
    brand: "Yoveo",
    rating: 2.9,
  },
  {
    id: 10,
    name: "vel",
    price: 1061,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 55,
    availability: false,
    brand: "Jaxspan",
    rating: 2.5,
  },
  {
    id: 11,
    name: "leo maecenas pulvinar",
    price: 389,
    currency: "Rs",
    image: ["https://picsum.photos/200/300"],
    discount: 25,
    availability: false,
    brand: "Skiptube",
    rating: 0.1,
  },
  {
    id: 12,
    name: "id lobortis convallis",
    price: 921,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 60,
    availability: true,
    brand: "Fivechat",
    rating: 3.7,
  },
  {
    id: 13,
    name: "primis in",
    price: 1128,
    currency: "Rs",
    image: ["https://picsum.photos/200/300"],
    discount: 35,
    availability: true,
    brand: "Browsetype",
    rating: 1.9,
  },
  {
    id: 14,
    name: "nulla",
    price: 1142,
    currency: "Rs",
    image: ["https://picsum.photos/200/300"],
    discount: 30,
    availability: true,
    brand: "Zoomcast",
    rating: 4.5,
  },
  {
    id: 15,
    name: "at ipsum",
    price: 1809,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 40,
    availability: false,
    brand: "Kazu",
    rating: 0.2,
  },
  {
    id: 16,
    name: "sem duis",
    price: 1242,
    currency: "Rs",
    image: ["https://picsum.photos/200/300"],
    discount: 40,
    availability: false,
    brand: "Twinder",
    rating: 3.5,
  },
  {
    id: 17,
    name: "in magna",
    price: 1980,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 55,
    availability: false,
    brand: "Vimbo",
    rating: 4.9,
  },
  {
    id: 18,
    name: "fusce consequat",
    price: 1478,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 60,
    availability: true,
    brand: "Jaloo",
    rating: 1.4,
  },
  {
    id: 19,
    name: "fusce",
    price: 416,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 55,
    availability: true,
    brand: "Zava",
    rating: 2.6,
  },
  {
    id: 20,
    name: "cras in purus",
    price: 97,
    currency: "Rs",
    image: ["https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    discount: 55,
    availability: true,
    brand: "Meevee",
    rating: 2.7,
  },
];
